name: chat_app
description: "Flutter chat app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # For Firebase initialization
  cloud_firestore: ^5.4.4  # For real-time database
  firebase_auth: ^5.3.1  # For auth (we'll use custom for OTP)
  flutter_chat_ui: ^1.6.14  # Delightful chat UI package for message bubbles
  flutter_chat_types: ^3.6.2
  mailer: ^6.1.3  # For sending OTP emails
  shared_preferences: ^2.3.2  # For local storage of user token
  uuid: ^4.5.1  # For generating unique IDs
  intl: ^0.19.0  
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
